# ==============================================================================
#               CI/CD Workflow: Build and Push Streamlit App
# ==============================================================================
#
# Workflow Name: A descriptive name for this specific automated process.
name: Build and Push States App Image

# This workflow triggers on every 'push' event to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# --- CUSTOMIZABLE VARIABLES ---
env:
  # A new, unique name for your Streamlit app's Docker image on Docker Hub.
  DOCKERHUB_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/states-app

# --- WORKFLOW JOBS ---
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # --- Step 1: Get the Code ---
      - name: 'Step 1: Checkout Repository Code'
        uses: actions/checkout@v4

      # --- Step 2: Set up Docker Build Environment ---
      - name: 'Step 2: Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      # --- Step 3: Log in to Docker Hub ---
      - name: 'Step 3: Log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Step 4: Build and Push the Docker Image ---
      - name: 'Step 4: Build, Tag, and Push Docker Image'
        uses: docker/build-push-action@v5
        with:
          # context is '.', since the Dockerfile is in the root of this repo.
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE_NAME }}:latest,${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
          # Caching is enabled to speed up future builds.
          cache-from: type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:buildcache,mode=max
